title = "如月 飛羽"
baseURL = "https://flyingfeather1501.github.io"
languageCode = "zh-tw"
config = "config.toml"
theme = "hugo_theme_robust"
disqusShortname = "kisaragi-hiu-blog"

[params]
  #dateformat = "2001/01/01"
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700"
  fontfamily = "Overpass,'Noto Sans CJK','Noto Sans',sans-serif" # Optional, Override body font family.
  logofontfamily = "'Noto Serif','Noto Serif CJK', serif" # Optional, Override logo font.

[outputs]
  page = [ "HTML", "AMP" ] # enable AMP
