baseURL = "https://flyingfeather1501.github.io"
languageCode = "zh-tw"
title = "如月.飛羽"
config = "config.toml"
theme = "hugo-phlat-theme"

[params]
  keywords = ["default", "keywords", "if", "no", "front", "matter"]
  description = "A description that will appear as a default if front matter does not exist"
  disqus = "kisaragi-hiu-blog"
  twitter = "https://www.twitter.com/flyin1501"
  youtube = "https://www.youtube.com/channel/UCl_hsqcvdX0XdgBimRQ6R3A"

[permalinks]
  post = "/:year/:month/:slug/"
  page = "/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.header]]
  name = "Home"
  weight = 1
  url = "/"

[[menu.header]]
  name = "Links"
  weight = 2
  url = "/links/"

[[menu.header]]
  name = "About"
  weight = 3
  url = "/about/"
